### ISSUE TITLE
WebSocket usage C# sample code is hanging (or encountering errors)

### ISSUE THREAD

**Issue by vivegi** [Idirect-Tech/Breeze-CSharp-SDK#2]
WebSocket usage C# sample code is hanging (or encountering errors).
Here is the log generated by the application.

<pre>
Created BreezeConnect object
Generated session as per version
Reconnected after 173615 attempts. to hosturl https://livefeeds.icicidirect.com/
Socket-Id: szzdCuvh5LqDA1XhANme
{"Result":{"Success":null,"Status":500,"Error":"Socket connection already established. for order streaming"},"Id":1,"Exception":null,"Status":5,"IsCanceled":false,"IsCompleted":true,"IsCompletedSuccessfully":true,"CreationOptions":0,"AsyncState":null,"IsFaulted":false}
Reconnected after 262145 attempts. to hosturl https://breezeapi.icicidirect.com/
Socket-Id: 2QmJ4Gk91dlwYg5_c1pd
{"Result":{"Success":null,"Status":500,"Error":"Socket connection already established. for ohlc streaming"},"Id":2,"Exception":null,"Status":5,"IsCanceled":false,"IsCompleted":true,"IsCompletedSuccessfully":true,"CreationOptions":0,"AsyncState":null,"IsFaulted":false}
Reconnected after 9999 attempts. to hosturl https://livestream.icicidirect.com/
Socket-Id: lBJ32zOY6HmC4tU1Aobi
{"Success":null,"Status":500,"Error":"Socket connection already established. FOR rate refresh"}
Connected to Websocket
</pre>

I had made minor modifications to the sample code as follows:

<pre>
<code>
      // Read the configuration [ADDED]
      Config config = ReadConfiguration("algotrade.config.json");

      // Initialize SDK 
      BreezeConnect breeze = new BreezeConnect(config.ApiKey);
      Console.WriteLine("Created BreezeConnect object");
                
      // Generate Session
      breeze.generateSessionAsPerVersion(config.SecretKey, config.SessionToken);
      Console.WriteLine("Generated session as per version");

      // Connect to WebSocket
      var responseObject = await breeze.wsConnectAsync();
      Console.WriteLine(JsonSerializer.Serialize(responseObject));
      Console.WriteLine("Connected to Websocket");

      // Callback to receive ticks.
      breeze.ticker((data) =>
      {
          Console.WriteLine("Ticker Data:" + JsonSerializer.Serialize(data));
       });
       Console.WriteLine("Registered callback for ticks");
                
       // Subscribe stocks feeds
       // err 1: See: https://github.com/Idirect-Tech/Breeze-CSharp-SDK/issues/1
       // arguments updated -- strikePrice, expiryDate
       Console.WriteLine(JsonSerializer.Serialize(await breeze.subscribeFeedsAsync(exchangeCode: "NFO", stockCode: "ICIBAN", productType: "options", expiryDate: "29-Mar-2023", strikePrice: "800", right: "Put", getExchangeQuotes: true, getMarketDepth: false)));
       Console.WriteLine("Subscribed to feeds for ICIBAN");

                /* COMMENTED OUT IN THIS SAMPLE
                // Subscribe stocks feeds by stock-token
                Console.WriteLine(JsonSerializer.Serialize(await breeze.subscribeFeedsAsync("4.1!49937")));
                Console.WriteLine("Subscribed to feeds for 4.1!49937");

                // Subscribe order notification feeds to get order data
                Console.WriteLine(JsonSerializer.Serialize(await breeze.subscribeFeedsAsync(getOrderNotification: true)));
                Console.WriteLine("Subscribed to order data feeds");

                // UnSubscribe order notification feeds
                // no async
                //Console.WriteLine(JsonSerializer.Serialize(await breeze.unsubscribeFeedsAsync(getOrderNotification: true)));
                Console.WriteLine(JsonSerializer.Serialize(breeze.unsubscribeFeeds(getOrderNotification: true)));
                END OF COMMENTED FRAGMENT */

       // Unsubscribe stocks feeds
       Console.WriteLine(JsonSerializer.Serialize(await breeze.unsubscribeFeedsAsync(exchangeCode: "NFO", stockCode: "ICIBAN", productType: "options", expiryDate: "25-Aug-2022", strikePrice: "650", right: "Put", getExchangeQuotes: true, getMarketDepth: false)));
       Console.WriteLine("Unsubscribed stock feeds");
</code>
</pre>

I was expecting the ticks callback to be called, however, that doesn't seem to be the case as shown in the response object

<pre>
{"Success":null,"Status":500,"Error":"Socket connection already established. FOR rate refresh"}
</pre>

If I let the application run for a little bit longer, I get the following logs on the console:

<pre>
... omitted for brevity ...

Rewatch successfull
{"Result":{"Success":null,"Status":500,"Error":"Fail to establish Socket connection. for order streaming"},"Id":111057,"Exception":null,"Status":5,"IsCanceled":false,"IsCompleted":true,"IsCompletedSuccessfully":true,"CreationOptions":0,"AsyncState":null,"IsFaulted":false}
{"Result":{"Success":null,"Status":500,"Error":"Socket connection already established. for ohlc streaming"},"Id":111058,"Exception":null,"Status":5,"IsCanceled":false,"IsCompleted":true,"IsCompletedSuccessfully":true,"CreationOptions":0,"AsyncState":null,"IsFaulted":false}
reconnection established
Rewatch successfull
{"Result":{"Success":null,"Status":500,"Error":"Fail to establish Socket connection. for order streaming"},"Id":111059,"Exception":null,"Status":5,"IsCanceled":false,"IsCompleted":true,"IsCompletedSuccessfully":true,"CreationOptions":0,"AsyncState":null,"IsFaulted":false}
{"Result":{"Success":null,"Status":500,"Error":"Socket connection already established. for ohlc streaming"},"Id":111060,"Exception":null,"Status":5,"IsCanceled":false,"IsCompleted":true,"IsCompletedSuccessfully":true,"CreationOptions":0,"AsyncState":null,"IsFaulted":false}
reconnection established

... omitted for brevity ...
</pre>

Please help with resolving this issue and proceeding further.

**Comment by vivegi** [comment]
Looking into this further, here are a few more comments. I am using <code>net7.0</code>. I notice the following in the [BreezeConnect.cs](https://github.com/Idirect-Tech/Breeze-CSharp-SDK/blob/developer/BreezeConnect.cs) source code:

<pre>
        public void generateSessionAsPerVersion(string secretKey, string sessionToken, bool debug = false)
        {
#if NET472_OR_GREATER
                        this.generateSessionUsingHttpHandler(secretKey, sessionToken);
#else
            this.generateSession(secretKey, sessionToken);
#endif

        }
</pre>

The <code>generateSessionAsPerVersion</code> method is using a conditional compilation based on dotnet version. So, I tried calling <code>generateSessionUsingHttpHandler</code> directly and discovered another issue.

<pre>
public async void generateSessionUsingHttpHandler(string secretKey, string sessionToken, bool debug = false)
</pre>

Notice the problem? It is using <code>async void</code>. This means the caller (i.e., my program) cannot <code>await</code> for this method to complete. It looks like this method is setting session data on the socket handlers.

<pre>
_socketHandler.setSession(userId: decodedString.Split(separator: ':')[0], sessionToken: decodedString.Split(separator: ':')[1], tokenScriptDictList: getStockScriptList(), debug: debug, apiKey: _apiKey);
_socketHandlerOrder.setSession(userId: decodedString.Split(separator: ':')[0], sessionToken: decodedString.Split(separator: ':')[1], tokenScriptDictList: getStockScriptList(), debug: debug, apiKey: _apiKey);
</pre>

Obviously, this means subsequent calls that my program makes are on a breeze object in invalid state as can be seen in this error log:

<pre>
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Breeze.BreezeConnect.generateSessionUsingHttpHandler(String secretKey, String sessionToken, Boolean debug)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
System.AggregateException: One or more errors occurred. (Cannot initiate connection to server. UserId or SessionToken is empty.)
 ---> System.Exception: Cannot initiate connection to server. UserId or SessionToken is empty.
   at Breeze.SocketEventBreeze.initiateSocketIOOptions(Boolean isOhlcv)
   at Breeze.SocketEventBreeze.ConnectForOrder()
   at Breeze.BreezeConnect.wsConnectAsyncOrder()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at Breeze.BreezeConnect.wsConnectAsync()
   at algotrade.Engine.Run() in .\algotrade\Program.cs:line 41
</pre>

Clearly, the error is happening at <code>wsConnectAsync</code> because the async function <code>generateSessionUsingHttpHandler</code> has still not finished because of the <code>async void</code> issue.

See: https://learn.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming for Async/Await best practices.

As is, the websocket API for C# is unusable because of this bug and it is a showstopper. Please help.

**Comment by ShrikantOneture** [comment]
if you are using net6.0 or above, please try calling generateSession, for netframework version generateSessionUsingHttpHandler is used.

**Comment by ShrikantOneture** [comment]
please use the code of pre_release branch, which went to live last time,  we gonna move it master branch in few days.

**Comment by ShrikantOneture** [comment]
Dear user , when you are subscribing to ordernotification = True, it is expected to place order in order to receive tick data, the sample you have provided, i dont see place order being called.

Also, for getting tick_by_tick market data you just have to subscribe stock_token.
for order notification you have to subscribe getordernotification flag followed by placing order.

**Comment by vivegi** [comment]
> if you are using net6.0 or above, please try calling generateSession, for netframework version generateSessionUsingHttpHandler is used.

I tried that too. It didn't work. 

Is it possible to provide a complete C# .NET project sample (for the supported and tested version) so that I can compile it on my machine and just run it with my api/secret/session keys?

**Comment by vivegi** [comment]
> Dear user , when you are subscribing to ordernotification = True, it is expected to place order in order to receive tick data, the sample you have provided, i dont see place order being called.
> 
> Also, for getting tick_by_tick market data you just have to subscribe stock_token. for order notification you have to subscribe getordernotification flag followed by placing order.

In my sample code, all of that had been commented out. The only operative part is this:

<pre>
      // Generate Session (I have also tried breeze.generateSession(), doesn't work)
      breeze.generateSessionAsPerVersion(config.SecretKey, config.SessionToken);
      Console.WriteLine("Generated session as per version");

      // Connect to WebSocket
      var responseObject = await breeze.wsConnectAsync();
      Console.WriteLine(JsonSerializer.Serialize(responseObject));
      Console.WriteLine("Connected to Websocket");

      // Callback to receive ticks.
      breeze.ticker((data) =>
      {
          Console.WriteLine("Ticker Data:" + JsonSerializer.Serialize(data));
       });
       Console.WriteLine("Registered callback for ticks");
                
       // Subscribe stocks feeds
       // err 1: See: https://github.com/Idirect-Tech/Breeze-CSharp-SDK/issues/1
       // arguments updated -- strikePrice, expiryDate
       Console.WriteLine(JsonSerializer.Serialize(await breeze.subscribeFeedsAsync(exchangeCode: "NFO", stockCode: "ICIBAN", productType: "options", expiryDate: "29-Mar-2023", strikePrice: "800", right: "Put", getExchangeQuotes: true, getMarketDepth: false)));
       Console.WriteLine("Subscribed to feeds for ICIBAN");
</pre>

I get the output of <code>Console.WriteLine("Connected to Websocket");</code> but nothing after that. Shouldn't the tick data be logged when the callback is called. That doesn't seem to happen.

**Comment by ShrikantOneture** [comment]
try out tomorrow in market hours

**Comment by ShrikantOneture** [comment]
try subscribing some stock let say reliance whose stock token is "4.1!2885" ,see if u are receiving feeds.

**Comment by vijayinvites** [comment]
Why is this closed without fixing? I am getting the same issue. What is the resolution for this?

**Comment by Idirect-Tech** [comment]
Dear Client,

Requested to share the code snippet without credentials(Api and Secret Key) at breezeapi@icicisecurities.com.

**Comment by Idirect-Tech** [comment]
Dear Arun,

Thank you for showing interest in Breeze API.

Please share a screenshot of the payload you're passing when subscribing to WebSocket.

[E29CF836]
Thanks & Regards,
Akash Sapkal,
Team Breeze API,
ICICI Securities

________________________________
